AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Cloudformation template for a monitoring exercise on Edrans onboarding.

Metadata:
  Instances:
    Description: "Testing of parameters in Cloudformation"
Parameters: 
  InstanceType:
    Type: String
  ImageId: 
    Type: String
  AvailabilityZone: 
    Type: String
  IamInstanceProfile:
    Type: String
  KeyName:
    Type: String

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref ImageId
      IamInstanceProfile: !Ref IamInstanceProfile
      KeyName: !Ref KeyName
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'test-anita-edrans'
